[package]
name = "ctvtcntr"
version = "0.1.0"
edition = "2021"



[dependencies]
ctrlc = "3.4.6"
hyprland = "0.4.0-beta.2"
serde = {version = "1.0.217", features  = ["derive"]}
csv = "1.3.1"
chrono = "0.4.39"
tracing = "0.1.41"
regex = "0.2.11"
tracing-subscriber = "0.3.19"
