name: Rust

on:
  push:
    branches: [ "master", "duck_db_implementation" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          sudo apt-get update
          sudo apt-get install -y libduckdb-dev # not needed when using duckdb "bundled" feature
          cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
